server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: Lucky@server2002

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
