server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Lucky@server2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
      import: configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true

#Configuration related to resilience4j circuit breaker and retry
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

  resilience4j:
    circuitbreaker:
      instance:
        ratingHotelBreaker:
          registerHealthIndicator: true
          eventConsumerBufferSize: 10
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 6s
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          slidingWindowType: COUNT_BASED

  retry:
    instance:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 2s

  ratelimiter:
    instance:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s